* Assignment 1

Link to assignment walkthrough video: [[https://youtu.be/Owqp3MIZG9E][link]] 

* First time only setup

- Accept this GitHub assignment by following
  this [[https://classroom.github.com/a/BKJdJVBT][link]].


Once finished, click on the repo link (or go to your GitHub account
and then to this new repo). clone by doing the following (you may have already done this by following the video and instructions on the main page) :

1. Log in to [[https://repl.it][repl.it]] using GitHub (see material and video on main page if you need assistance)
2. click on the *+ create repl" button
3. click on the *import from GitHub* button
4. Type in the full name of your repo (something like hunter-teacher-cert/applicants-prework-for-cohort-3-githubusername)


* Every time you work

1. Log into repl.it using GitHUb
2. Open this repl
3. click on the version control button and if it says you need updates from GitHub, click the button


* Assignment

1. Click on the *new folder* icon from the file tree section of repl and add a folder named *pre01*
2. Click on that folder and create a new file under it named *Hello.Java*
   - Note: if you place the folder in the wrong location you can either drag and drop it or delete by clicking on it in the file tree and selecting delete and then creating a new file.
4. Click on the file *Hello.java* and add the following contents:

 #+begin_src java
   import java.io.*;
   import java.util.*;

   public class Hello {
       public static void main(String[] args){
           System.out.println("Hello world!");
       }
   }
 #+end_src

5. From the right hand pane on repl.it click the "shell" tab. You should see the area below set up as a terminal where you can type.
6. Type *ls* and hit enter. *ls* is a command that lists the contents of a folder or directory
   You should see README.org and 01 listed and maybe some other files or folders.
7. Type *cd 01* and hit enter. This will move the shell into the *01* folder. 
8. Type *ls* and hit enter. You should see *Hello.java* listed.

Now you can compile the program *Hello.java* by typing *javac Hello.java* and hiting enter. If you see any errors, fix them by editing the program. If the error is "file not found" make sure the terminal is in the right folder by typing the *pwd* command and hitting enter. You can cd back to the main directory/folder by typign *cd* and hitting enter and then go back into 01 with *cd 01* as before.

If you don't get errors type *ls* and you should see a new file naemd *Hello.class*. This is the Java bytcode file that you can run under the Java virtual machine. 

To run your program, type *java Hello* - note that you don't add the .class, it's just Hello. 

If everyting works, you should see *Hello World!* on the screen. If not, try to fix your errors.


Put an error in your program - remove a quote or a bracket and
recompile using ~javac Hello.java~ - read the error. Fix it and try to
generate another error. Finally fix and text the program again so that
it works.

As a final step, yuou have to push the code back up to GitHub

1. Click the version control button on the right.
2. Add a message saying what you changed.
3. click the commit and push button
4. Go to GitHub and look to make sure your new program is there.

Congratulations!!!!!!

You just wrote your first Java program.


References for this assignment:
| Reference        | Chapter(s)   |
|------------------+--------------|
| [[https://books.trinket.io/thinkjava/][Think Java]]       | 1            |
| [[https://introcs.cs.princeton.edu/java/10elements/][Sedgwick / Wayne]] | 1.1.1, 1.1.2 |
| [[https://chortle.ccsu.edu/Java5/index.html#03][ Kjell]]           | 1 through 7  |

 Please review and consider the questions at the end of the chapters.

Congratulations again, you've successfully written your first program
and pushed it to GitHub!!!!!
