* Assignment 6 - Loops


References for this assignment:
| Reference        | Chapter(s) |
|------------------+------------|
| [[https://books.trinket.io/thinkjava/][Think Java]]       |         7 |
| [[https://introcs.cs.princeton.edu/java/10elements/][Sedgwick / Wayne]] |        1.3 |
| [[https://chortle.ccsu.edu/Java5/index.html#03][Kjell]]            |      15-20 |


Read Chapter 7 of Think Java.

Short example video: [[https://www.youtube.com/watch?v=h5ofkIw-sCs&list=PL9KxKa8NpFxJF3PmYcixDqBv28Sqi0q6o&index=7][link]]


Java has loops that are very similar to Javascript. The Java while
loop is essentially the same as the Python while loop but the for loop
is a little different. The differences are outlined below:

*** While
The Java ~while~ loop is pretty much the same as the javscript or
Python while 

#+begin_src java
// Example A
while (boolean)
  statement;

// Example B
while (boolean) {
  statemnts;
}

#+end_src

While you don't need the brackets if you only have a single statement,
it's considered bad form to omit them. 

*** for

Java's ~for~ loop is similar to Javscript but not the same as
Python's. The Python for loop is considered a ~foreach~ loop and we'll
look at Java's equivalent later.

The Java and Javascript for loops are really just a while loop in
disguise.

Let's look at this while loop:

#+begin_src java
a = 1; // INITIALIZION
while (a < 10){  // TEST
  do stuff;
  a = a + 1; // INCREMENT
}

#+end_src

In addition to the stuff you're doing, there are three basic
parts. The INITIALIZATION ~a=1~ which sets the starting value of the
loop variable, the TEST which is ~a<10~ which determines when the loop
terminates adn the INCREMENT of ~a=a+1~ which changes the value of the
test so that we eventually exit.

A for loop is of the form: 
#+begin_src java
for (INITIALIZATION, TEST, INCREMENT) {
  do stuff;
}
#+end_src

so the above while loop can be rewritten using a for: 
#+begin_src 
for (a=1; a<10; a++){
  do stuff;
}

#+end_src

That's all it is - just a shorthand for writing a while loop.


*** do while

Java also supports a do while but it's used less frequently. The
chapter will go over the details.


* For submission
Place all of these in a folder named ~pre06~

All book references are for [[https://books.trinket.io/thinkjava][Think Java]].

| Chapter/section | Exercise | Filename       |
|-----------------+----------+----------------|
|             7.9 |        1 | See note below |
|             7.9 |    2,3,4 | See Note       |
| 
** Note:

Complete exercise 1 from Chapter 7.9 of Think Java. Either type up your
answer in a file named answer.txt or write it by hand and scan it into
answer.pdf. Add the file to a folder named ~pre03~ in the assignments
repo and push to GitHub.

For exercises 2,3, and 4 create a file named Loops.java and create
methods for each exercise. Name them as you see fit. When the program
is run, all the methods should be called and results printed out. 

* Submission

Create a directory named pre06 under your assignments repo. Write a
program named ~Loops.java~ which has solutions to excercises 2,3, and4from chapter 7 of Think Java.


