* Assignment 4 - Conditionals

References for this assignment:
| Reference        | Chapter(s) |
|------------------+------------|
| [[https://books.trinket.io/thinkjava/][Think Java]]       |          5 |
| [[https://introcs.cs.princeton.edu/java/10elements/][Sedgwick / Wayne]] |      1.3.1 |
| [[https://chortle.ccsu.edu/Java5/index.html#03][Kjell]]            |      12-14 |

Read chapter 5 in Think Java.

Short example Video: [[https://www.youtube.com/watch?v=Wb0edysSxfA&list=PL9KxKa8NpFxJF3PmYcixDqBv28Sqi0q6o&index=5][link]]

*NOTE:* I accidentally used pre05 as the folder name in the video. The
folder name should be pre04 as indicated in the actual assignment
below.


This section covers conditionals. Java *if* statements look
pretty much the same as those in Javascript

* Conditionals

#+begin_src java
  // Example A - simple if
  if (boolean) 
    statement; 

  // Example B - if with compound statement
  if (boolean){
      statement1;
      statement2;
      ...;
      statementn;
  }

  // Example C - if with else
  if (boolean){
      statements;
  } else {
      statements;
  }

  // Example D - if with else chain
  if (boolean1) {
      statements;
  } else if (boolean2) {
      statements;
  } else {
      statements;
  }

#+end_src

In Examples B through D, if you don't have multiple statements in each
section you don't need that sections curly braces but it's generally
considered good form to use them. Also, Example D can have any number
of ~else if~ sections.

A Python *if* is similar but different due to its use of indentation
instead of brackets and the explicit elif as opposed to the Java ~else
if~.

* For submission
Place all of these in a folder named ~pre04~

All book references are for [[https://books.trinket.io/thinkjava][Think Java]].

| Chapter/section | Exercise | Filename       |
|-----------------+----------+----------------|
|            5.12 | 1,2,3    | See note below |
|            5.12 | 5        | Beer.java      |

** Note:

For exercises 1,2, and 3 either type up your
answer in a file named answer.txt or write it by hand and scan it into
answer.pdf. Add the file to a folder named ~pre04~ in the assignments
repo and push to GitHub.

